# Generated by Django 5.2.7 on 2026-01-15 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Krótki opis kawy.')),
                ('coffee_strength', models.IntegerField(help_text='Moc kawy w skali od 1-5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('coffee_acidity', models.IntegerField(help_text='Kwasowość kawy w skali od 1-3.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('loyalty_points', models.PositiveIntegerField(default=0, help_text='Aktualna liczba punktów lojalnościowych klienta.')),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('BR', 'BRAZYLIA'), ('VN', 'WIETNAM'), ('CO', 'KOLUMBIA'), ('ET', 'ETIOPIA'), ('ID', 'INDONEZJA'), ('UG', 'UGANDA')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Klient, który złożył zamówienie.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.customer')),
            ],
            options={
                'ordering': ['-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Z', 'Ziarnista'), ('M', 'Mielona'), ('K', 'Kapsułki')], default='Z', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cena kawy w PLN.', max_digits=5)),
                ('taste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.coffeetaste')),
                ('producent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.producent')),
            ],
        ),
    ]
