# Generated by Django 6.0.1 on 2026-01-23 22:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Krótki opis kawy.')),
                ('coffee_strength', models.IntegerField(help_text='Moc kawy w skali od 1-5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('coffee_acidity', models.IntegerField(help_text='Kwasowość kawy w skali od 1-3.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('BR', 'BRAZYLIA'), ('VN', 'WIETNAM'), ('CO', 'KOLUMBIA'), ('ET', 'ETIOPIA'), ('ID', 'INDONEZJA'), ('UG', 'UGANDA')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coffeetype', models.CharField(choices=[('Z', 'Ziarnista'), ('M', 'Mielona'), ('K', 'Kapsułki')], default='Z', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cena kawy w PLN.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('taste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.coffeetaste')),
                ('producent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.producent')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(help_text='Klient, który złożył zamówienie.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sklep.customer')),
            ],
            options={
                'ordering': ['-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_order', models.DecimalField(decimal_places=2, help_text='Cena kawy w momencie złożenia zamówienia.', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('coffee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.coffee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sklep.order')),
            ],
        ),
    ]
